# fly.toml app configuration file generated for aibe1-project2-team05-embedding on 2025-05-06T06:38:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aibe1-project2-team05-embedding'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
