app = 'aibe1-project2-team05-embedding'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  # 헬스체크 설정
  [[http_service.checks]]
    grace_period = "180s"
    interval = "30s"
    method = "GET"
    path = "/"
    timeout = "10s"
    restart_limit = 3

[env]
  PORT = "5000"
  HOST = "0.0.0.0"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048